[project]
name = "ttsdb"
version = "0.1.0"
description = "A unified API for TTS inference."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.49.1",
    "gradio-client>=1.13.3",
    "librosa>=0.11.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
