display_name: "Bark Small"
url: https://github.com/suno-ai/bark
license: https://github.com/suno-ai/bark/blob/main/LICENSE
release_date: 2023-04-28
training_data: null
training_hours: null
languages:
  - en
  - de
  - es
  - it
  - ja
  - pl
  - pt
  - tr
num_parameters: 240M
representations:
  - audio codec
  - encodec
features:
  - non-autoregressive
  - autoregressive
  - grapheme-to-phoneme
  - language modeling
citations: >
  @misc{Bark2023,
    author = {Suno},
    title = {Bark},
    year = {2023},
    publisher = {GitHub},
    journal = {GitHub repository},
    howpublished = {\url{https://github.com/suno-ai/bark}},
    commit = {f4f32d4cd480dfec1c245d258174bc9bde3c2148}
  }
  @misc{BarkVC2023,
    author = {Mylo},
    title = {Bark Voice Cloning HuBERT Quantizer},
    year = {2023},
    publisher = {GitHub},
    journal = {GitHub repository},
    howpublished = {\url{https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer}},
    commit = {4f42e44480fb076a52ddeb1f5ec6132d3c1ad25a}
  }
api:
  identifier: ttsds/bark_small
  version: e0e4df86d3dd484bcb7b693077929005d4222d1bbdccf7afed3eccee06b0bbea
  parameters:
    text: text
    speaker_reference: speaker_reference
    text_reference: null
    language: language
