display_name: "GPT-SoVITS v2"
paper: null
url: https://github.com/RVC-Boss/GPT-SoVITS
license: https://github.com/RVC-Boss/GPT-SoVITS/blob/main/LICENSE
release_date: 2024-08-07
languages:
  - en
  # - zh - not working at the moment
  - ja
  - ko
  - yue
training_data: null
training_hours: 5000
num_parameters: 200M
representations:
  - audio codec
features:
  - non-autoregressive
  - autoregressive
  - grapheme-to-phoneme
  - language modeling
citations: >
  @misc{RVCBoss2024,
    author = {RVC-Boss},
    title = {GPT-SoVITS},
    year = {2024},
    publisher = {GitHub},
    journal = {GitHub repository},
    howpublished = {\url{https://github.com/RVC-Boss/GPT-SoVITS}},
  }
api:
  identifier: ttsds/gptsovits_2
  version: 7b49064a36acf3a00679ab61a41efb0370a0dbfcddd42509934400439372f43c
  parameters:
    text: text
    speaker_reference: speaker_reference
    language: language
    text_reference: text_reference