display_name: "MaskGCT"
paper: https://arxiv.org/abs/2304.09116
url: https://github.com/open-mmlab/Amphion
license: https://github.com/open-mmlab/Amphion/blob/main/LICENSE
release_date: 2024-10-17
languages:
  - en
  - zh
training_data: Emilia
training_hours: 100000
num_parameters: 1B
representations:
  - semantic tokens
  - w2v-bert
features:
  - non-autoregressive
  - masked training
citations: >
  @article{wang2024maskgct,
    title={MaskGCT: Zero-Shot Text-to-Speech with Masked Generative Codec Transformer},
    author={Wang, Yuancheng and Zhan, Haoyue and Liu, Liwei and Zeng, Ruihong and Guo, Haotian and Zheng, Jiachen and Zhang, Qiang and Zhang, Xueyao and Zhang, Shunsi and Wu, Zhizheng},
    journal={arXiv preprint arXiv:2409.00750},
    year={2024}
  }
  @inproceedings{amphion,
      author={Zhang, Xueyao and Xue, Liumeng and Gu, Yicheng and Wang, Yuancheng and Li, Jiaqi and He, Haorui and Wang, Chaoren and Song, Ting and Chen, Xi and Fang, Zihao and Chen, Haopeng and Zhang, Junan and Tang, Tze Ying and Zou, Lexiao and Wang, Mingxuan and Han, Jun and Chen, Kai and Li, Haizhou and Wu, Zhizheng},
      title={Amphion: An Open-Source Audio, Music and Speech Generation Toolkit},
      booktitle={{IEEE} Spoken Language Technology Workshop, {SLT} 2024},
      year={2024}
  }
api:
  identifier: ttsds/amphion_maskgct
  version: 619089fed0a4ac2651ca4a30734f4e1c3d7f67e21a282d56e6f2bfba187e1a28
  parameters:
    text: text
    language: language
    speaker_reference: speaker_reference
    text_reference: text_reference