display_name: "OpenVoice v2"
paper: https://arxiv.org/abs/2312.01479
url: https://github.com/myshell-ai/OpenVoice
license: https://github.com/myshell-ai/OpenVoice/blob/main/LICENSE
release_date: 2024-04-23
languages:
  - en
  - zh
  - es
  # - ja fix support
  # - ko
  - fr
training_data: null
training_hours: null
num_parameters: null
representations:
  - mel spectrogram
features:
  - non-autoregressive
  - grapheme-to-phoneme
  - prosody prediction
  - diffusion
citations: >
  @article{qin2023openvoice,
    title={Openvoice: Versatile instant voice cloning},
    author={Qin, Zengyi and Zhao, Wenliang and Yu, Xumin and Sun, Xin},
    journal={arXiv preprint arXiv:2312.01479},
    year={2023}
  }
api:
  identifier: ttsds/openvoice_2
  version: 795fe9c3fc9d3d4cfac1ca97d8c8d33b522b42068daec53ab3c74f775dd506c8
  parameters:
    text: text
    speaker_reference: speaker_reference
    language: language
    text_reference: null