display_name: "XTTS v1"
paper: https://arxiv.org/abs/2406.04904
url: https://github.com/coqui-ai/TTS
license: https://github.com/coqui-ai/TTS/blob/main/LICENSE
release_date: 2023-12-01
languages:
  - en
  - es
  - fr
  - de
  - it
  - pt
  - pl
  - tr
  - ru
  - nl
  - cs
  - ar
  # - zh
  # - ja fix support
  - hu
  - ko
  - hi
training_data:
  - LibriTTS
  - CommonVoice
  - Unknown
training_hours: null
num_parameters: 466M
representations:
  - vq-vae
features:
  - autoregressive
  - language model
  - vq-vae
citations: >
  @article{casanova2024xtts,
    title={Xtts: a massively multilingual zero-shot text-to-speech model},
    author={Casanova, Edresson and Davis, Kelly and G{\"o}lge, Eren and G{\"o}knar, G{\"o}rkem and Gulea, Iulian and Hart, Logan and Aljafari, Aya and Meyer, Joshua and Morais, Reuben and Olayemi, Samuel and others},
    journal={arXiv preprint arXiv:2406.04904},
    year={2024}
  }
api:
  identifier: ttsds/xtts_1
  version: a1aa52ca3c189352e8173d47a5ead612da01d1b92b89d969f50be43a879c8758
  parameters:
    text: text
    speaker_reference: speaker_reference
    text_reference: null
    language: language